apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-claim
  namespace: j23milli
spec:
  # storageClassName: standard-rwo # voir kubectl get storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
